import { useState, useEffect, useRef, useMemo } from "react";
import { Layout } from "@/components/Layout";
import { useAuth } from "@/contexts/AuthContext";
import { useRbac } from "@/contexts/RbacContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import { Plus, Wallet, Paperclip, FileText, Search, CalendarIcon, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { EmptyState } from "@/components/EmptyState";
import { Loader } from "@/components/ui/loader";
import { accountsApi, accountParticularsApi } from "@/lib/api";
import type { AccountEntryDto, AccountParticularDto } from "@/lib/api";
import { z } from "zod";
import { format } from "date-fns";
import { formatTableDate } from "@/lib/utils";
import { cn } from "@/lib/utils";

const accountSchema = z
  .object({
    date: z.string().min(1, "Date is required"),
    particular: z.string().max(500).refine((v) => (v ?? "").trim().length > 0, "Particular is required"),
    description: z.string().max(1000).optional(),
    type: z.enum(["received", "expense"]),
    amount: z
      .string()
      .min(1, "Amount is required")
      .refine((v) => !isNaN(Number(v)) && Number(v) > 0, "Please enter a valid amount greater than zero."),
    paidTo: z.string().max(100).optional(),
  })
  .refine((data) => data.type !== "expense" || (String(data.paidTo ?? "").trim().length > 0), {
    message: "Paid To is required for expense",
    path: ["paidTo"],
  });

const emptyForm = {
  date: "",
  particular: "",
  description: "",
  type: "expense" as "received" | "expense",
  amount: "",
  paidTo: "",
  attachmentFileName: "" as string,
  attachmentData: "" as string,
};

function getFreshNewEntryForm() {
  return {
    ...emptyForm,
    date: new Date().toISOString().slice(0, 10),
    type: "expense" as const,
  };
}

function readFileAsBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result;
      if (typeof result === "string") resolve(result);
      else reject(new Error("Expected string"));
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

function formatLedgerMoney(value: number): string {
  return value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function generateVoucherPreview(date: string, type: "received" | "expense"): string {
  if (!date) return "—";
  try {
    const d = new Date(date);
    const year = d.getFullYear();
    const monthNames = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
    const month = monthNames[d.getMonth()];
    const prefix = type === "expense" ? "CL" : "DR";
    // Preview format - actual number will be generated by backend
    return `ATL/${year}/${month}/${prefix}01`;
  } catch {
    return "—";
  }
}

export default function Accounts() {
  const { isAdmin } = useAuth();
  const { isPageScopeAdmin } = useRbac();
  /** Accounts RBAC "user" is treated as admin in API; UI matches full admin actions. */
  const canManageAccounts = isAdmin || isPageScopeAdmin("accounts");
  const [entries, setEntries] = useState<AccountEntryDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingEntry, setEditingEntry] = useState<AccountEntryDto | null>(null);
  const [form, setForm] = useState(emptyForm);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [saveAction, setSaveAction] = useState<null | "close" | "new">(null);
  const [search, setSearch] = useState("");
  const [filterType, setFilterType] = useState<"all" | "received" | "expense">("all");
  const [dateRange, setDateRange] = useState<{ from?: Date; to?: Date }>({});
  const [receivedParticulars, setReceivedParticulars] = useState<AccountParticularDto[]>([]);
  const [expenseParticulars, setExpenseParticulars] = useState<AccountParticularDto[]>([]);
  const [addParticularOpen, setAddParticularOpen] = useState(false);
  const [newParticularName, setNewParticularName] = useState("");
  const [addingParticular, setAddingParticular] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const currentParticulars = form.type === "received" ? receivedParticulars : expenseParticulars;

  const fetchParticulars = () => {
    accountParticularsApi.list({ type: "received" }).then(setReceivedParticulars).catch(() => {});
    accountParticularsApi.list({ type: "expense" }).then(setExpenseParticulars).catch(() => {});
  };

  const fetchEntries = () => {
    setLoading(true);
    const fromStr = dateRange.from ? format(dateRange.from, "yyyy-MM-dd") : undefined;
    const toStr = dateRange.to ? format(dateRange.to, "yyyy-MM-dd") : undefined;
    const params = fromStr || toStr ? { from: fromStr, to: toStr } : undefined;
    accountsApi
      .list(params)
      .then(setEntries)
      .catch(() => toast.error("Failed to load account entries"))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchEntries();
  }, [dateRange.from, dateRange.to]);

  useEffect(() => {
    if (open) fetchParticulars();
  }, [open]);

  const filteredEntries = useMemo(() => {
    let list = entries;
    if (filterType === "received") list = list.filter((e) => (e.amountDebit ?? 0) > 0);
    else if (filterType === "expense") list = list.filter((e) => (e.amountCredit ?? 0) > 0);
    const q = search.trim().toLowerCase();
    if (q) {
      list = list.filter(
        (e) =>
          (e.particular ?? "").toLowerCase().includes(q) ||
          (e.description ?? "").toLowerCase().includes(q) ||
          (e.voucherNo ?? "").toLowerCase().includes(q) ||
          (e.paidBy ?? "").toLowerCase().includes(q) ||
          (e.paidTo ?? "").toLowerCase().includes(q)
      );
    }
    return list;
  }, [entries, filterType, search]);

  const totalDebit = useMemo(() => filteredEntries.reduce((sum, e) => sum + (e.amountDebit ?? 0), 0), [filteredEntries]);
  const totalCredit = useMemo(() => filteredEntries.reduce((sum, e) => sum + (e.amountCredit ?? 0), 0), [filteredEntries]);
  const totalBalance = totalDebit - totalCredit;

  const resetForm = () => {
    setForm({ ...emptyForm });
    setErrors({});
    setEditingId(null);
    setEditingEntry(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const openCreate = () => {
    setErrors({});
    setForm(getFreshNewEntryForm());
    setEditingId(null);
    setEditingEntry(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
    setOpen(true);
  };

  const handleAddParticular = async () => {
    const name = newParticularName.trim();
    if (!name) {
      toast.error("Enter a name");
      return;
    }
    setAddingParticular(true);
    try {
      const created = await accountParticularsApi.create({ name, type: form.type });
      fetchParticulars();
      setForm((f) => ({ ...f, particular: created.name }));
      setNewParticularName("");
      setAddParticularOpen(false);
      toast.success("Particular added");
    } catch {
      toast.error("Failed to add particular");
    } finally {
      setAddingParticular(false);
    }
  };

  const openEdit = (entry: AccountEntryDto) => {
    setForm({
      date: entry.date?.slice(0, 10) ?? "",
      particular: entry.particular ?? "",
      description: entry.description ?? "",
      type: entry.amountDebit > 0 ? "received" : "expense",
      amount: entry.amountDebit > 0 ? String(entry.amountDebit) : String(entry.amountCredit),
      paidTo: entry.paidTo ?? "",
      attachmentFileName: entry.attachmentFileName ?? "",
      attachmentData: "",
    });
    setEditingId(entry.id);
    setEditingEntry(entry);
    setErrors({});
    setOpen(true);
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    try {
      const base64 = await readFileAsBase64(file);
      setForm((f) => ({ ...f, attachmentFileName: file.name, attachmentData: base64 }));
    } catch {
      toast.error("Failed to read file");
    }
  };

  const handleSave = async (afterSave: "close" | "new") => {
    if (editingId && afterSave === "new") return;

    const result = accountSchema.safeParse({
      date: form.date,
      particular: form.particular,
      description: form.description,
      type: form.type,
      amount: form.amount,
      paidTo: form.paidTo,
    });
    if (!result.success) {
      const fieldErrors: Record<string, string> = {};
      result.error.errors.forEach((e) => {
        fieldErrors[e.path[0] as string] = e.message;
      });
      setErrors(fieldErrors);
      return;
    }

    setSaving(true);
    setSaveAction(afterSave);
    setErrors({});
    try {
      const amount = parseFloat(result.data.amount);
      const payload = {
        date: result.data.date,
        particular: (result.data.particular ?? "").trim(),
        description: (result.data.description ?? "").trim(),
        type: result.data.type,
        amount,
        paidTo: (result.data.paidTo ?? "").trim(),
        attachmentFileName: form.attachmentFileName || undefined,
        attachmentData: form.attachmentData || undefined,
      };
      if (editingId) {
        await accountsApi.update(editingId, {
          date: payload.date,
          particular: payload.particular,
          description: payload.description,
          type: payload.type,
          amount: payload.amount,
          paidTo: payload.paidTo,
          attachmentFileName: payload.attachmentFileName,
          attachmentData: form.attachmentData || undefined,
        });
        toast.success("Entry updated");
        fetchEntries();
        resetForm();
        setOpen(false);
      } else {
        await accountsApi.create(payload);
        toast.success("Entry added");
        fetchEntries();
        if (afterSave === "close") {
          resetForm();
          setOpen(false);
        } else {
          setErrors({});
          setForm(getFreshNewEntryForm());
          setEditingId(null);
          setEditingEntry(null);
          if (fileInputRef.current) fileInputRef.current.value = "";
        }
      }
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Request failed");
      setErrors({ submit: err instanceof Error ? err.message : "Request failed" });
    } finally {
      setSaving(false);
      setSaveAction(null);
    }
  };

  return (
    <Layout>
      <div className="flex flex-wrap gap-3 mb-4 items-center text-sm">
        <div className="relative flex-1 min-w-[180px] max-w-xs">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search particular, description, voucher…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>
        <Select value={filterType} onValueChange={(v) => setFilterType(v as "all" | "received" | "expense")}>
          <SelectTrigger className="w-36"><SelectValue placeholder="Type" /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All types</SelectItem>
            <SelectItem value="received">Received</SelectItem>
            <SelectItem value="expense">Expense</SelectItem>
          </SelectContent>
        </Select>
        <Popover>
          <PopoverTrigger asChild>
            <Button variant="outline" className={cn("w-56 justify-start text-left font-normal text-sm", !dateRange.from && "text-muted-foreground")}>
              <CalendarIcon className="h-4 w-4 mr-2" />
              {dateRange.from ? (dateRange.to ? `${format(dateRange.from, "PP")} – ${format(dateRange.to, "PP")}` : format(dateRange.from, "PP")) : "Date range"}
            </Button>
          </PopoverTrigger>
          <PopoverContent className="w-auto p-0" align="start">
            <Calendar
              mode="range"
              selected={dateRange.from ? { from: dateRange.from, to: dateRange.to } : undefined}
              onSelect={(range) => setDateRange({ from: range?.from, to: range?.to })}
              numberOfMonths={2}
              captionLayout="dropdown"
              fromYear={2020}
              toYear={2030}
              className={cn("p-3 pointer-events-auto")}
            />
          </PopoverContent>
        </Popover>
        {(dateRange.from || dateRange.to) && (
          <Button variant="ghost" size="sm" onClick={() => setDateRange({})}>Clear dates</Button>
        )}
        <div className="flex-1" />
        {canManageAccounts && (
          <Button onClick={openCreate}>
            <Plus className="h-4 w-4 mr-2" />
            Add Journal
          </Button>
        )}
      </div>

      {loading ? (
        <Loader message="Loading…" size="lg" className="py-16" />
      ) : entries.length === 0 ? (
        <EmptyState
          icon={Wallet}
          title={dateRange.from || dateRange.to ? "No entries in this date range" : "No account entries yet"}
          description={dateRange.from || dateRange.to ? "Try a different date range." : "Add received or expense entries."}
          actionLabel={canManageAccounts && !dateRange.from && !dateRange.to ? "Add entry" : undefined}
          onAction={canManageAccounts && !dateRange.from && !dateRange.to ? openCreate : undefined}
        />
      ) : filteredEntries.length === 0 ? (
        <EmptyState
          icon={Wallet}
          title="No entries match your filters"
          description="Try adjusting search, type, or date range."
        />
      ) : (
        <div className="data-table">
          <Table className="table-fixed w-full font-sans [&_tbody_tr]:min-h-12 [&_tbody_td]:min-h-12 [&_tbody_td]:align-middle [&_th]:font-sans [&_td]:font-sans">
            <colgroup>
              <col style={{ width: "10%" }} />
              <col style={{ width: "12%" }} />
              <col style={{ width: "20%" }} />
              <col style={{ width: "12%" }} />
              <col style={{ width: "12%" }} />
              <col style={{ width: "12%" }} />
              <col style={{ width: "11%" }} />
              <col style={{ width: "11%" }} />
            </colgroup>
            <TableHeader className="bg-muted/50 [&_tr]:h-12 [&_th]:text-sm">
              <TableRow>
                <TableHead className="whitespace-nowrap">Date</TableHead>
                <TableHead>Particular</TableHead>
                <TableHead className="hidden md:table-cell">Description</TableHead>
                <TableHead className="text-right">
                  Debit ({formatLedgerMoney(totalDebit)})
                </TableHead>
                <TableHead className="text-right">
                  Credit ({formatLedgerMoney(totalCredit)})
                </TableHead>
                <TableHead className="text-right">
                  Balance ({formatLedgerMoney(totalBalance)})
                </TableHead>
                <TableHead>Paid By</TableHead>
                <TableHead>Paid To</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredEntries.map((entry) => (
                <TableRow
                  key={entry.id}
                  className={cn(canManageAccounts && "cursor-pointer hover:bg-muted/30 transition-colors")}
                  onClick={() => canManageAccounts && openEdit(entry)}
                >
                  <TableCell className="text-sm whitespace-nowrap">{formatTableDate(entry.date)}</TableCell>
                  <TableCell className="truncate text-sm">{entry.particular || "—"}</TableCell>
                  <TableCell className="truncate hidden md:table-cell text-muted-foreground text-sm">{entry.description || "—"}</TableCell>
                  <TableCell className="text-right text-emerald-600 dark:text-emerald-400 text-sm">
                    {entry.amountDebit > 0 ? formatLedgerMoney(entry.amountDebit) : "—"}
                  </TableCell>
                  <TableCell className="text-right text-red-600 dark:text-red-400 text-sm">
                    {entry.amountCredit > 0 ? formatLedgerMoney(entry.amountCredit) : "—"}
                  </TableCell>
                  <TableCell className="text-right font-medium text-sm">
                    {formatLedgerMoney(entry.balance ?? 0)}
                  </TableCell>
                  <TableCell className="text-sm text-muted-foreground">{entry.paidBy || "—"}</TableCell>
                  <TableCell className="text-sm text-muted-foreground">{entry.paidTo || "—"}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}

      <Dialog open={open} onOpenChange={(v) => { setOpen(v); if (!v) resetForm(); }}>
        <DialogContent
          showClose={false}
          className="flex max-h-[min(92dvh,calc(100vh-1rem))] w-[calc(100vw-1rem)] max-w-[calc(100vw-1rem)] flex-col gap-0 overflow-hidden p-0 sm:w-full sm:max-w-[min(100vw-1.25rem,40rem)] md:max-w-[min(100vw-1.5rem,48rem)] lg:max-w-[min(100vw-2rem,56rem)] xl:max-w-[min(100vw-2.5rem,64rem)] 2xl:max-w-[min(100vw-3rem,72rem)]"
        >
          <DialogHeader
            className={cn(
              "shrink-0 space-y-0 border-b border-border p-4 sm:p-5",
              form.type === "received"
                ? "bg-emerald-50 dark:bg-emerald-950"
                : "bg-orange-50 dark:bg-orange-950",
            )}
          >
            <div className="flex min-w-0 flex-nowrap items-center justify-between gap-2 sm:gap-3">
              <div className="flex min-w-0 flex-1 items-center gap-2 sm:gap-2.5">
                <div
                  className={cn(
                    "shrink-0 rounded-xl p-2 shadow-sm sm:p-2.5",
                    form.type === "received" ? "bg-emerald-500 text-white" : "bg-orange-500 text-white",
                  )}
                >
                  <Wallet className="h-4 w-4 sm:h-5 sm:w-5" />
                </div>
                <DialogTitle className="m-0 min-w-0 truncate text-left text-lg font-semibold sm:text-xl">
                  {editingId ? "Edit Account Entry" : "New Account Entry"}
                </DialogTitle>
              </div>
              <div className="flex min-w-0 max-w-full items-center gap-2 sm:gap-2.5">
                <div className="min-w-0 text-right">
                  <p className="text-[9px] font-semibold uppercase leading-none tracking-wide text-muted-foreground sm:text-[10px]">
                    Voucher
                  </p>
                  <p
                    className={cn(
                      "mt-0.5 max-w-[min(100%,14rem)] truncate font-mono text-xs font-bold tabular-nums sm:max-w-[18rem] sm:text-sm",
                      form.type === "received"
                        ? "text-emerald-800 dark:text-emerald-200"
                        : "text-orange-800 dark:text-orange-200",
                    )}
                    title={editingEntry?.voucherNo || generateVoucherPreview(form.date, form.type)}
                  >
                    {editingEntry?.voucherNo || generateVoucherPreview(form.date, form.type)}
                  </p>
                </div>
                <div
                  className={cn(
                    "shrink-0 rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wide sm:px-2.5 sm:text-xs",
                    form.type === "received"
                      ? "bg-emerald-600 text-white shadow-sm dark:bg-emerald-700"
                      : "bg-orange-600 text-white shadow-sm dark:bg-orange-700",
                  )}
                >
                  {form.type === "received" ? "Debit" : "Credit"}
                </div>
              </div>
            </div>
            <p className="sr-only">
              {editingId
                ? "Voucher number cannot be changed."
                : "Preview voucher number; final number is assigned when you save."}
            </p>
          </DialogHeader>

          <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain bg-gradient-to-b from-background to-muted/20">
            <div className="flex flex-col gap-4 p-4 sm:gap-5 sm:p-5 lg:p-6">
              <div className="flex min-w-0 flex-col gap-4 sm:gap-5">
                {/* Row 1: four fields on lg / xl */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4 lg:gap-4">
                  <div className="min-w-0 space-y-2">
                    <Label className="flex items-center gap-1 text-sm font-semibold text-foreground">
                      Date <span className="text-destructive">*</span>
                    </Label>
                    <Input
                      type="date"
                      value={form.date}
                      onChange={(e) => setForm((f) => ({ ...f, date: e.target.value }))}
                      className="h-10 border-2 transition-colors focus:border-primary sm:h-11"
                    />
                    {errors.date && <p className="mt-1 text-sm text-destructive">{errors.date}</p>}
                  </div>
                  <div className="min-w-0 space-y-2">
                    <Label className="flex items-center gap-1 text-sm font-semibold text-foreground">
                      Entry Type <span className="text-destructive">*</span>
                    </Label>
                    <Select
                      value={form.type}
                      onValueChange={(v) =>
                        setForm((f) => ({
                          ...f,
                          type: v as "received" | "expense",
                          particular: "",
                          paidTo: v === "expense" ? f.paidTo : "",
                        }))
                      }
                    >
                      <SelectTrigger
                        className={cn(
                          "h-10 border-2 font-medium transition-colors sm:h-11",
                          form.type === "received"
                            ? "border-emerald-200 bg-emerald-50/50 focus:border-emerald-400"
                            : "border-orange-200 bg-orange-50/50 focus:border-orange-400",
                        )}
                      >
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="z-[200]">
                        <SelectItem value="received">Received (Debit)</SelectItem>
                        <SelectItem value="expense">Expense (Credit)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="min-w-0 space-y-2 sm:col-span-2 lg:col-span-1">
                    <Label className="flex items-center gap-1 text-sm font-semibold text-foreground">
                      Particular <span className="text-destructive">*</span>
                    </Label>
                    <Select
                      value={form.particular || "none"}
                      onValueChange={(v) => setForm((f) => ({ ...f, particular: v === "none" ? "" : v }))}
                    >
                      <SelectTrigger className="h-10 border-2 transition-colors focus:border-primary sm:h-11">
                        <SelectValue placeholder="Select particular" />
                      </SelectTrigger>
                      <SelectContent className="z-[200]">
                        <SelectItem value="none">— Select particular —</SelectItem>
                        {currentParticulars.map((p) => (
                          <SelectItem key={p.id} value={p.name}>
                            {p.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    {errors.particular && <p className="mt-1 text-sm text-destructive">{errors.particular}</p>}
                  </div>
                  <div className="min-w-0 space-y-2 sm:col-span-2 lg:col-span-1">
                    <Label className="flex items-center gap-1 text-sm font-semibold text-foreground">
                      Amount <span className="text-destructive">*</span>
                    </Label>
                    <div className="relative">
                      <span className="absolute left-3 top-1/2 -translate-y-1/2 text-lg font-bold text-muted-foreground sm:left-4">
                        ৳
                      </span>
                      <Input
                        type="number"
                        className="h-10 border-2 pl-9 text-lg font-bold transition-colors focus:border-primary sm:h-11 sm:pl-10 sm:text-xl"
                        value={form.amount}
                        onChange={(e) => setForm((f) => ({ ...f, amount: e.target.value }))}
                        placeholder="0.00"
                        step="0.01"
                      />
                    </div>
                    {errors.amount && <p className="mt-1 text-sm text-destructive">{errors.amount}</p>}
                  </div>
                </div>

                {/* Description + transaction context side by side on lg */}
                <div className="grid grid-cols-1 gap-4 lg:grid-cols-2 lg:gap-5">
                  <div className="min-w-0 space-y-2">
                    <Label className="text-sm font-semibold text-foreground">Description</Label>
                    <textarea
                      className="flex min-h-[72px] w-full resize-none rounded-lg border-2 border-input bg-background px-3 py-2.5 text-sm transition-colors focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-ring lg:min-h-[100px]"
                      value={form.description}
                      onChange={(e) => setForm((f) => ({ ...f, description: e.target.value }))}
                      placeholder="Add a detailed description for this transaction..."
                    />
                  </div>

                  <div
                    className={cn(
                      "rounded-xl border-2 p-4 shadow-sm transition-all sm:p-5",
                      form.type === "received"
                        ? "border-emerald-200/50 bg-gradient-to-br from-emerald-50/30 to-emerald-100/10"
                        : "border-orange-200/50 bg-gradient-to-br from-orange-50/30 to-orange-100/10",
                    )}
                  >
                    <h4 className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground sm:mb-4 sm:text-xs">
                      <div
                        className={cn(
                          "rounded-md p-1.5",
                          form.type === "received" ? "bg-emerald-100 dark:bg-emerald-900/40" : "bg-orange-100 dark:bg-orange-900/40",
                        )}
                      >
                        <FileText
                          className={cn(
                            "h-3 w-3",
                            form.type === "received" ? "text-emerald-600 dark:text-emerald-400" : "text-orange-600 dark:text-orange-400",
                          )}
                        />
                      </div>
                      Transaction Context
                    </h4>
                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 sm:gap-4">
                      <div className="space-y-1 sm:space-y-2">
                        <Label className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground sm:text-xs">
                          Paid By
                        </Label>
                        <p
                          className={cn(
                            "text-sm font-semibold sm:text-base",
                            form.type === "received"
                              ? "text-emerald-700 dark:text-emerald-300"
                              : "text-orange-700 dark:text-orange-300",
                          )}
                        >
                          {form.type === "received" ? "Apptriangle" : "Petty Cash"}
                        </p>
                      </div>
                      <div className="space-y-1 sm:space-y-2">
                        <Label className="flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground sm:text-xs">
                          {form.type === "expense" ? (
                            <>
                              Paid To <span className="text-destructive">*</span>
                            </>
                          ) : (
                            "Paid To"
                          )}
                        </Label>
                        {form.type === "received" ? (
                          <p
                            className={cn(
                              "text-sm font-semibold sm:text-base",
                              form.type === "received"
                                ? "text-emerald-700 dark:text-emerald-300"
                                : "text-orange-700 dark:text-orange-300",
                            )}
                          >
                            Petty Cash
                          </p>
                        ) : (
                          <>
                            <Input
                              className="h-9 border-2 bg-background transition-colors focus:border-primary sm:h-10"
                              value={form.paidTo}
                              onChange={(e) => setForm((f) => ({ ...f, paidTo: e.target.value }))}
                              placeholder="Enter recipient name"
                            />
                            {errors.paidTo && <p className="mt-1 text-sm text-destructive">{errors.paidTo}</p>}
                          </>
                        )}
                      </div>
                    </div>
                  </div>
                </div>

                {/* Attachment — full width */}
                <div className="flex flex-col gap-3 rounded-lg border border-dashed border-muted-foreground/30 bg-muted/30 p-3 sm:flex-row sm:items-center sm:p-4">
                  <input ref={fileInputRef} type="file" className="hidden" onChange={handleFileChange} />
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => fileInputRef.current?.click()}
                    className="w-full border-2 transition-colors hover:bg-muted sm:w-auto"
                  >
                    <Paperclip className="mr-2 h-4 w-4" />
                    {form.attachmentFileName ? "Replace File" : "Attach Receipt"}
                  </Button>
                  {form.attachmentFileName && (
                    <div className="flex min-w-0 flex-1 items-center gap-2">
                      <FileText className="h-4 w-4 shrink-0 text-muted-foreground" />
                      <span className="truncate text-sm font-medium text-foreground">{form.attachmentFileName}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="flex shrink-0 flex-col-reverse gap-3 border-t border-border bg-muted/80 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5">
            <Button
              type="button"
              variant="outline"
              onClick={() => setOpen(false)}
              disabled={saving}
              className="h-10 w-full border-2 border-slate-500 bg-white px-6 font-semibold text-slate-900 shadow-sm hover:bg-slate-100 hover:text-slate-950 dark:border-slate-400 dark:bg-slate-900 dark:text-slate-50 dark:hover:bg-slate-800 sm:h-11 sm:w-auto"
            >
              Cancel
            </Button>
            <div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:justify-end sm:gap-3">
              {!editingId && (
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => handleSave("new")}
                  disabled={saving}
                  className={cn(
                    "h-10 w-full border-2 font-semibold shadow-sm sm:h-11 sm:min-w-[10rem]",
                    form.type === "received"
                      ? "border-emerald-700 bg-emerald-50 text-emerald-950 hover:bg-emerald-100 hover:text-emerald-950 dark:border-emerald-400 dark:bg-emerald-950/90 dark:text-emerald-50 dark:hover:bg-emerald-900 dark:hover:text-white"
                      : "border-orange-700 bg-orange-50 text-orange-950 hover:bg-orange-100 hover:text-orange-950 dark:border-orange-400 dark:bg-orange-950/90 dark:text-orange-50 dark:hover:bg-orange-900 dark:hover:text-white",
                  )}
                >
                  {saving && saveAction === "new" ? (
                    <span className="flex items-center justify-center gap-2">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Saving…
                    </span>
                  ) : (
                    "Save & New"
                  )}
                </Button>
              )}
              <Button
                type="button"
                onClick={() => handleSave("close")}
                disabled={saving}
                className={cn(
                  "h-10 w-full px-8 font-semibold shadow-md transition-all hover:shadow-lg sm:h-11 sm:min-w-[10rem]",
                  form.type === "received"
                    ? "bg-emerald-600 text-white hover:bg-emerald-700"
                    : "bg-orange-600 text-white hover:bg-orange-700",
                )}
              >
                {saving && saveAction === "close" ? (
                  <span className="flex items-center justify-center gap-2">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Saving…
                  </span>
                ) : (
                  "Save & Exit"
                )}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      <Dialog open={addParticularOpen} onOpenChange={setAddParticularOpen}>
        <DialogContent className="max-w-sm">
          <DialogHeader><DialogTitle>Add Particular</DialogTitle></DialogHeader>
          <div className="space-y-4 pt-4">
            <div className="space-y-2">
              <Label>Name *</Label>
              <Input value={newParticularName} onChange={(e) => setNewParticularName(e.target.value)} />
            </div>
            <Button onClick={handleAddParticular} disabled={addingParticular} className="w-full">
              {addingParticular ? "Adding..." : "Add"}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </Layout>
  );
}